name: Schedule Update Check

on:
  schedule:
    - cron: '0 3 * * *'  # Ежедневно в 3:00 UTC (6:00 по Москве)
  workflow_dispatch:  # Ручной запуск

jobs:
  check-schedule:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    
    - name: Install dependencies
      run: pip install -r requirements.txt
    
    - name: Run schedule parser
      run: python scripts/schedule_parser.py
      env:
        TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
        TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
    
    - name: Commit and push if changed
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add schedule.ics last_hash.txt
        git diff --cached --quiet || (git commit -m "Update schedule $(date +'%Y-%m-%d %H:%M')" && git push)